name: Manifest check

on:
  workflow_call:
    secrets: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  manifest-check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jonzudell/manifest/manifest:${{ vars.MANIFEST_IMAGE_TAG }}
      options: --user 1001
    env:
      MANIFEST_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10000

      - name: Manifest inspection
        run: |
          /home/manifestuser/start_cmd.sh
