name: Manifest check

on:
  workflow_call:
    secrets: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jonzudell/manifest/manifest:v0.0.3
    env:
      MANIFEST_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10000

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Configure Git safe directory
        run: git config --global --add safe.directory /__w/$(echo ${{ github.event.repository.name }} | cut -d'/' -f2)/$(echo ${{ github.event.repository.name }} | cut -d'/' -f2)

      - name: Fetch target branch
        run: git fetch --depth=1 origin ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }}
        
      - name: Manifest inspection
        run: git diff origin/${{ github.event.pull_request.base.ref }}...HEAD | manifest inspect --sha ${{ github.event.pull_request.head.sha }} --formatter github --strict