name: Use Manifest Check Head

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  call-manifest-check-head:
    needs: publish-image
    uses: ./.github/workflows/manifest-check.yml
    with:
      MANIFEST_IMAGE_TAG: latest